"""
Advanced Storage Cleaner & Verification Engine for REN-AI Windows Control Center
Provides:
- Itemized scanning of Windows junk, temp files, shader caches, crash dumps, and Recycle Bin.
- Zero-destruction preview before any deletion occurs.
- Safe cleaning: handles file locks gracefully without crashing.
- Verification pass: confirms actual megabytes reclaimed.
"""

import os
import shutil
import tempfile
import ctypes
from pathlib import Path
from typing import Dict, List, Any, Optional

try:
    from .history import change_history
except ImportError:
    from history import change_history


class CleanupItem:
    """Represents a category of cleanable disk cache."""

    def __init__(
        self,
        item_id: str,
        title: str,
        description: str,
        paths: List[Path],
        safe_to_clean: bool = True,
    ):
        self.item_id = item_id
        self.title = title
        self.description = description
        self.paths = paths
        self.safe_to_clean = safe_to_clean
        self.file_count = 0
        self.total_bytes = 0

    @property
    def total_mb(self) -> float:
        return round(self.total_bytes / (1024 * 1024), 2)

    def to_dict(self) -> Dict[str, Any]:
        return {
            "id": self.item_id,
            "title": self.title,
            "description": self.description,
            "file_count": self.file_count,
            "total_bytes": self.total_bytes,
            "total_mb": self.total_mb,
            "safe_to_clean": self.safe_to_clean,
        }


class StorageCleaner:
    """Scans, previews, cleans, and verifies Windows storage junk."""

    def __init__(self):
        self._items: Dict[str, CleanupItem] = {}
        self._init_targets()

    def _init_targets(self):
        local_appdata = Path(os.environ.get("LOCALAPPDATA", str(Path.home() / "AppData/Local")))
        windir = Path(os.environ.get("WINDIR", r"C:\Windows"))

        self._items = {
            "user_temp": CleanupItem(
                item_id="user_temp",
                title="User Temporary Files",
                description="Temporary runtime files generated by user applications.",
                paths=[Path(tempfile.gettempdir())],
            ),
            "system_temp": CleanupItem(
                item_id="system_temp",
                title="Windows System Temp",
                description="Temporary installation and update files in Windows Temp.",
                paths=[windir / "Temp"],
            ),
            "delivery_optimization": CleanupItem(
                item_id="delivery_optimization",
                title="Delivery Optimization Cache",
                description="Cached peer-to-peer Windows Update files.",
                paths=[windir / "SoftwareDistribution" / "DeliveryOptimization"],
            ),
            "crash_dumps": CleanupItem(
                item_id="crash_dumps",
                title="Crash Dumps & Error Reports",
                description="Memory crash minidumps and Windows Error Reporting logs.",
                paths=[
                    local_appdata / "CrashDumps",
                    windir / "Minidump",
                    Path(os.environ.get("PROGRAMDATA", r"C:\ProgramData")) / "Microsoft" / "Windows" / "WER",
                ],
            ),
            "shader_caches": CleanupItem(
                item_id="shader_caches",
                title="DirectX & GPU Shader Caches",
                description="Compiled graphics shader caches from DirectX, Nvidia, and AMD.",
                paths=[
                    local_appdata / "D3DSCache",
                    local_appdata / "NVIDIA" / "DXCache",
                    local_appdata / "AMD" / "DxCache",
                ],
            ),
            "thumbnail_cache": CleanupItem(
                item_id="thumbnail_cache",
                title="Thumbnail Cache",
                description="Cached thumbnail icons generated by Windows File Explorer.",
                paths=[local_appdata / "Microsoft" / "Windows" / "Explorer"],
            ),
        }

    def scan_all(self) -> Dict[str, CleanupItem]:
        """
        Scans all target paths and calculates file counts and reclaimable bytes.
        """
        for item in self._items.values():
            file_count = 0
            total_bytes = 0

            for p in item.paths:
                try:
                    if not p.exists():
                        continue
                except (PermissionError, OSError):
                    continue

                try:
                    for root, _, files in os.walk(str(p)):
                        for f in files:
                            if item.item_id == "thumbnail_cache" and not f.startswith("thumbcache_"):
                                continue
                            fp = Path(root) / f
                            try:
                                sz = fp.stat().st_size
                                total_bytes += sz
                                file_count += 1
                            except (PermissionError, OSError):
                                pass
                except (PermissionError, OSError):
                    pass

            item.file_count = file_count
            item.total_bytes = total_bytes

        return self._items

    def clean_target(self, item_id: str) -> Dict[str, Any]:
        """
        Safely purges unneeded files in the specified category.
        """
        item = self._items.get(item_id)
        if not item:
            return {"success": False, "message": f"Target '{item_id}' not found."}

        initial_bytes = item.total_bytes
        deleted_count = 0
        freed_bytes = 0

        for p in item.paths:
            try:
                if not p.exists():
                    continue
            except (PermissionError, OSError):
                continue

            try:
                for entry in p.iterdir():
                    try:
                        if item.item_id == "thumbnail_cache" and not entry.name.startswith("thumbcache_"):
                            continue

                        if entry.is_file():
                            sz = entry.stat().st_size
                            entry.unlink()
                            freed_bytes += sz
                            deleted_count += 1
                        elif entry.is_dir():
                            shutil.rmtree(entry, ignore_errors=True)
                    except Exception:
                        continue
            except Exception:
                continue

        freed_mb = round(freed_bytes / (1024 * 1024), 2)
        # Re-scan item
        self.scan_all()

        return {
            "success": True,
            "target": item_id,
            "deleted_count": deleted_count,
            "freed_mb": freed_mb,
            "message": f"Cleaned {deleted_count} files from {item.title}, freeing {freed_mb} MB.",
        }

    def clean_all(self) -> Dict[str, Any]:
        """
        Cleans all scanned targets and reports summary.
        """
        total_freed_bytes = 0
        total_deleted_files = 0
        details = {}

        for item_id in self._items.keys():
            res = self.clean_target(item_id)
            total_deleted_files += res.get("deleted_count", 0)
            freed_mb = res.get("freed_mb", 0.0)
            total_freed_bytes += int(freed_mb * 1024 * 1024)
            details[item_id] = res

        total_mb = round(total_freed_bytes / (1024 * 1024), 2)
        return {
            "success": True,
            "total_deleted_files": total_deleted_files,
            "total_freed_mb": total_mb,
            "details": details,
            "message": f"Storage cleanup complete: Freed {total_mb} MB across {total_deleted_files} files.",
        }

    def empty_recycle_bin(self) -> Dict[str, Any]:
        """
        Empties Windows Recycle Bin using native Win32 Shell API.
        """
        try:
            # SHERB_NOCONFIRMATION = 0x00000001, SHERB_NOPROGRESSUI = 0x00000002, SHERB_NOSOUND = 0x00000004
            flags = 0x00000001 | 0x00000002 | 0x00000004
            res = ctypes.windll.shell32.SHEmptyRecycleBinW(None, None, flags)
            if res == 0:
                return {"success": True, "message": "Windows Recycle Bin emptied."}
            else:
                return {"success": True, "message": "Recycle Bin is already empty."}
        except Exception as e:
            return {"success": False, "message": f"Failed to empty Recycle Bin: {e}"}


storage_cleaner = StorageCleaner()
